services:
  mariadb:
    build: requirements/mariadb
    image: mariadb:mt_j
    container_name: mariadb
    env_file:
      - .env
    networks:
      - incepction
    volumes:
      - db:/var/lib/mysql
    restart: on-failure
  wordpress:
    build: requirements/wordpress
    image: wordpress:mt_j
    container_name: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpressFiles:/var/www/html/wordpress
    networks:
      - incepction
    restart: on-failure
  nginx:
    build: requirements/nginx
    image: nginx:mt_j
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - wordpressFiles:/var/www/html/wordpress
    networks:
      - incepction
    depends_on:
      - wordpress
    restart: on-failure
  adminer:
    build: requirements/bonus/adminer
    image: adminer:mt_j
    container_name: adminer
    networks:
      - incepction
    ports:
      - 8081:8080
    restart: on-failure
  cadvisor:
    build: requirements/bonus/cadvisor
    image: cadvisor:mt_j
    container_name: cadvisor
    networks:
      - incepction
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    restart: on-failure
  website:
    build: requirements/bonus/website
    image: website:mt_j
    container_name: website
    networks:
      - incepction
    ports:
      - 1337:80
    restart: on-failure
  redis:
    build: requirements/bonus/redis
    image: redis:mt_j
    container_name: redis
    networks:
      - incepction
    depends_on:
      - wordpress
    volumes:
      - wordpressFiles:/var/www/html
    restart: on-failure
  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp/
    image: ftp:mt_j
    volumes:
      - wordpressFiles:/home/mjlem/ftp/files
    env_file:
      - .env
    ports:
      - "21:21"
      - "20:20"
      - "40000-40005:40000-40005"
    networks:
      - incepction
    restart: on-failure

volumes:
  db:
    driver_opts:
      type: none
      o: bind
      device: /Users/mjlem/data/db
  wordpressFiles:
    driver_opts:
      type: none
      o: bind
      device: /Users/mjlem/data/wordpress
networks:
  incepction:
    name: incepction
  